config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  devise_for :users,
  			 path: '',
  			 path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
  			 controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :users, only: [:show]
  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  get '/your-trips' => 'reservations#your_trips'
  get '/your-reservations' => 'reservations#your_reservations'


  			 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :room

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :photos
  has_many :reservations

  geocoded_by :address	
  after_validation :geocode


  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :accommodate, presence: true
  validates :bedroom, presence: true
  validates :bathroom, presence: true

  

  def cover_photo(size)
  	if self.photos.length > 0
  	  self.photos[0].image.url(size)
  	else
  	  "blank.jpg"
  	end 
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :omniauthable, omniauth_providers: %i[facebook]

   has_many :rooms
   has_many :reservations


   # validates :fullname, presence: true, length: {maximum: 50}
	def self.from_omniauth(auth)

	  user = User.where(email: auth.info.email).first 		

	  if user 
	  	return user
	  else 
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
		    user.email = auth.info.email
		    user.password = Devise.friendly_token[0,20]
		    user.fullname = auth.info.fullname   
		    user.image = auth.info.image 
		    user.uid = auth.uid	
		    user.provider = auth.provider
		    user.skip_confirmation!		
	    end
	  end 
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected 

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:fullname, :phone, :description])
  end

end

app/controllers/omniauth_callbacks_controller.rb
class  OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController 

	def create
		@room = Room.find(params[:room_id])

		if params[:images]
			params[:images].each do |img|
				@room.photos.create(image: img)
			end
			@photos = @room.photos 
			redirect_back(fallback_location: request.referrer, notice: "Saved...")
		end
		
	end

	def destroy
		@photo = Photo.find(params[:id])
		@room = @photo.room

		@photo.destroy 
		@photos = Photo.where(room_id: @room.id)

		respond_to :js
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected 

  def update_resource(resource, params)
  	resource.update_without_password(params)
  end
end 

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController 
	before_action :authenticate_user!

	def create 
	  room = Room.find(params[:room_id])
	  start_date = Date.parse(reservations_params[:start_date])
	  end_date = Date.parse(reservations_params[:end_date])
	  days = (end_date - start_date).to_i + 1 

	  if current_user == room.user 
	  	flash[:alert] = "You cannot book your own property"
	  else
	  @reservation = current_user.reservations.build(reservations_params)
	  @reservation.room = room
	  @reservation.price = room.price 
	  @reservation.total = room.price * days 
	  @reservation.save 

	  flash[:notice] = "Booked Successfully!"
	  end 	
	  redirect_to room 
	end 

	def your_trips 
		@trips = current_user.reservations.order(start_date: :asc)
	end

	def your_reservations
		@rooms = current_user.rooms
		
	end

	private

	def reservations_params
		params.require(:reservation).permit(:start_date, :end_date)
	end
end 

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]
  before_action :is_authorised, only: [:listing, :pricing, :description, :photo_upload, :amenities, :location, :update]

  def index
    @rooms = current_user.rooms
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to listing_room_path(@room), notice: "Saved..."
    else
      flash[:alert] = "Something went wrong..."
      render :new
    end
  end

  def show
    @photos = @room.photos
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
    @photos = @room.photos
  end

  def amenities
  end

  def location
  end

  def update

    new_params = room_params
    new_params = room_params.merge(active: true) if is_ready_room

    if @room.update(new_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Something went wrong..."
    end
    redirect_back(fallback_location: request.referer)
  end

  # --- Reservations ---
  def preload
    today = Date.today
    reservations = @room.reservations.where("start_date >= ? OR end_date >= ?", today, today)

    render json: reservations
  end

  def preview
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])

    output = {
      conflict: is_conflict(start_date, end_date, @room)
    }

    render json: output
  end

  private
    def is_conflict(start_date, end_date, room)
      check = room.reservations.where("? < start_date AND end_date < ?", start_date, end_date)
      check.size > 0? true : false
    end

    def set_room
      @room = Room.find(params[:id])
    end

    def is_authorised
      redirect_to root_path, alert: "You don't have permission" unless current_user.id == @room.user_id
    end

    def is_ready_room
      !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank?
    end

    def room_params
      params.require(:room).permit(:home_type, :room_type, :accommodate, :bed_room, :bath_room, :listing_name, :summary, :address, :is_tv, :is_kitchen, :is_air, :is_heating, :is_internet, :price, :active)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
	def show
		@user = User.find(params[:id])
		@rooms = @user.rooms
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def avatar_url(user, size)	   
	   if user.image
	   	 "http://graph.facebook.com/#{user.uid}/picture?type=large" 
	   else 
		 gravatar_id = Digest::MD5::hexdigest(user.email).downcase
     	 url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
	   end

	end
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/_devise_message.html.erb
<% unless resource.errors.empty? %>
	<script type="text/javascript">
		<% resource.errors.full_messages.each do |value| %>
		 toastr.error('<%= value %>')
		<% end %>
	</script>
<% end %>

app/views/layouts/_message.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">
		<% flash.each do |key, value| %>
		 <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
		 toastr['<%= type %>']('<%= value %>')
		<% end %>
	</script>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container ">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'AirPikachu', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
      <li>
        <button class="btn btn-form btn-small nav-btn">
           <li><%= link_to "Become a host", new_room_path, style: "color: white; text-decoration: none; " %></li>
        </button>
      </li>
      <% if user_signed_in? %> 
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= image_tag avatar_url(current_user, 32), class: "img-circle avatar-small" %>
            <% if current_user.fullname == "" %>
              <%= current_user.email %>
            <% else %>
              <%= current_user.fullname %>
            <% end %>
          <span class="caret"></span>
        </a>
          <ul class="dropdown-menu">
           <li><%= link_to "Manage Listings", rooms_path %></li>
           <li><%= link_to "List Your Space", new_room_path %></li>
           <li><%= link_to "Your Reservations", your_reservations_path %></li>
           <li><%= link_to "Your Trips", your_trips_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li> 
          </ul>
        </li>
      <% else %>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to 'Log In', new_user_session_path %></li> 
      <% end %>   
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirPikachu</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/hot-sneaks/jquery-ui.css">
  </head>

  <body>
  	<%= render 'layouts/navbar' %>
    <%= render 'layouts/message' %>
    <div class="container">
      <%= yield %>    
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>

app/views/photos/_photos_list.html.erb
<% if @photos.count > 0 %>
  <br/><br/>

  <div class="row">
    <% @photos.each do |photo| %>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading preview">
            <%= image_tag photo.image.url() %>
          </div>
          <div class="panel-body">
            <span class="pull-right">
              <%= link_to room_photo_path(photo.room_id, photo), remote: true, method: :delete, data: {confirm: "Are you sure?"} do %>
                <i class="fa fa-trash-o fa-lg" aria-hidden="true"></i>
              <% end %>
            </span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/photos/destroy.js.erb
$('#photos').html("<%= j render 'photos_list' %>")
<% if @room.photos.blank? %>
  $('#photo_check').hide();
<% end %>

<% if !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank? %>
    $('#publish_button').attr('disabled', false);
<% else %>
    $('#publish_button').attr('disabled', true);
<% end %>

app/views/reservations/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <span><i class="fa fa-bolt" style="color: #ffb400"></i> $<%= @room.price %></span>
    <span class="pull-right">Per Night</span>
  </div>
  <div class="panel-body">
    <%= form_for([@room, @room.reservations.new]) do |f| %>
      <div class="row">
        <div class="col-md-6">
          <label>Check In</label>
          <%= f.text_field :start_date, readonly: true, placeholder: "Start Date", class: "form-control datepicker" %>
        </div>
        <div class="col-md-6">
          <label>Check Out</label>
          <%= f.text_field :end_date, readonly: true, placeholder: "End Date", class: "form-control datepicker", disabled: true %>
        </div>
      </div>

      <h4 class="message-alert text-center"><span id="message"></span></h4>
      <div id="preview" style="display: none">
        <table class="reservation-table">
          <tbody>
            <tr>
              <td>Price</td>
              <td class="text-right">$<%= @room.price %></td>
            </tr>
            <tr>
              <td>Night(s)</td>
              <td class="text-right">x <span id="reservation_nights"></span></td>
            </tr>
            <tr>
              <td class="total">Total</td>
              <td class="text-right">$<span id="reservation_total"></span></td>
            </tr>
          </tbody>
        </table>
      </div>

      <br/>

      <%= f.submit "Book Now", id: "btn_book", class: "btn btn-normal btn-block", disabled: true %>
    <% end %>
  </div>
</div>


<script>

  function checkDate(date) {
    dmy = date.getDate() + "-" + (date.getMonth() + 1) + "-" + date.getFullYear();
    return [$.inArray(dmy, unavailableDates) == -1];
  }

  $(function() {

    unavailableDates = [];

    $.ajax({
      url: '<%= preload_room_path(@room) %>',
      dateTyp: 'json',
      success: function(data) {

        $.each(data, function(arrID, arrValue) {
            for(var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() + 1)) {
              unavailableDates.push($.datepicker.formatDate('d-m-yy', d));
            }
        });

        $('#reservation_start_date').datepicker({
          dateFormat: 'dd-mm-yy',
          minDate: 0,
          maxDate: '3m',
          beforeShowDay: checkDate,
          onSelect: function(selected) {
            $('#reservation_end_date').datepicker("option", "minDate", selected);
            $('#reservation_end_date').attr("disabled", false);

            var start_date = $('#reservation_start_date').datepicker('getDate');
            var end_date = $('#reservation_end_date').datepicker('getDate');
            var nights = (end_date - start_date)/1000/60/60/24 + 1;

            var input = {
              'start_date': start_date,
              'end_date': end_date
            }

            $.ajax({
              url: '<%= preview_room_path(@room) %>',
              data: input,
              success: function(data) {

                if(data.conflict) {
                  $('#message').text("These dates are not available.");
                  $('#preview').hide();
                  $('#btn_book').attr('disabled', true);
                } else {
                  $('#message').text("");
                  $('#preview').show();
                  $('#btn_book').attr('disabled', false);

                  var total = nights * <%= @room.price %>
                  $('#reservation_nights').text(nights);
                  $('#reservation_total').text(total);
                }
              }
            });

          }
        });

        $('#reservation_end_date').datepicker({
          dateFormat: 'dd-mm-yy',
          minDate: 0,
          maxDate: '3m',
          beforeShowDay: checkDate,
          onSelect: function(selected) {
            $('#reservation_start_date').datepicker("option", "maxDate", selected);

            var start_date = $('#reservation_start_date').datepicker('getDate');
            var end_date = $('#reservation_end_date').datepicker('getDate');
            var nights = (end_date - start_date)/1000/60/60/24 + 1;

            var input = {
              'start_date': start_date,
              'end_date': end_date
            }

            $.ajax({
              url: '<%= preview_room_path(@room) %>',
              data: input,
              success: function(data) {

                if(data.conflict) {
                  $('#message').text("These dates are not available.");
                  $('#preview').hide();
                  $('#btn_book').attr('disabled', true);
                } else {
                  $('#message').text("");
                  $('#preview').show();
                  $('#btn_book').attr('disabled', false);

                  var total = nights * <%= @room.price %>
                  $('#reservation_nights').text(nights);
                  $('#reservation_total').text(total);
                }
              }
            });
          }
        });
      }
    });



  });
</script>

app/views/reservations/your_reservations.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", rooms_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Trips", your_trips_path, class: "sidebar-link" %></li>


    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Your Reservations
      </div>
      <div class="panel-body">

        <% @rooms.each do |room| %>
          <% room.reservations.each do |reservation| %>
            <div class="row">
              <div class="col-md-2">
                <%= reservation.start_date.strftime('%v') %>
              </div>
              <div class="col-md-2">
                <%= link_to room_path(reservation.room) do %>
                  <%= image_tag reservation.room.cover_photo(:thumb) %>
                <% end %>
              </div>
              <div class="col-md-8">
                <%= link_to reservation.room.listing_name, room_path(reservation.room) %> <br><br>

                <span>
                  <%= link_to user_path(reservation.user) do %>
                  <%= image_tag avatar_url(reservation.user, 32), class: "img-circle avatar-small" %> <br>
                  <%= reservation.user.fullname %>
                </span>
                <% end %>
              </div>
            </div>
            <hr>
          <% end %>
        <% end %>

                
              
 
      </div>
    </div>
  </div>
</div>

app/views/reservations/your_trips.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", rooms_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "Your Trips", your_trips_path, class: "sidebar-link active" %></li>


    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Your Trips
      </div>
      <div class="panel-body">

        <% @trips.each do |trip| %>
          <div class="row">
            <div class="col-md-2">
              <%= trip.start_date.strftime('%v') %>
            </div>
            <div class="col-md-2">
              <%= link_to room_path(trip.room) do %>
                <%= image_tag trip.room.cover_photo(:thumb) %>
              <% end %>
            </div>
            <div class="col-md-8">
              <%= link_to trip.room.listing_name, room_path(trip.room) %>
              <span class="pull-right text-center">
                <%= image_tag avatar_url(trip.room.user, 32), class: "img-circle avatar-medium" %> <br>
                <%= link_to user_path(trip.room.user) do %>
                  <%= trip.room.user.fullname %>
                <% end %>

              </span>

                
              
            </div>
          </div>
          <hr/>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/_photos_list.html.erb
<% if @photos.count > 0 %>
  <br/><br/>

  <div class="row">
    <% @photos.each do |photo| %>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading preview">
            <%= image_tag photo.image.url() %>
          </div>
          <div class="panel-body">
            <span class="pull-right">
              <%= link_to room_photo_path(photo.room_id, photo), remote: true, method: :delete, data: {confirm: "Are you sure?"} do %>
                <i class="fa fa-trash-o fa-lg" aria-hidden="true"></i>
              <% end %>
            </span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/rooms/_room_menu.html.erb
<ul class="sidebar-list">
  <li class="sidebar-item">
    <%= link_to "Listing", listing_room_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "Pricing", pricing_room_path, class: "sidebar-link active" %>
    <% if !@room.price.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Description", description_room_path, class: "sidebar-link active" %>
    <% if !@room.listing_name.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Photos", photo_upload_room_path, class: "sidebar-link active" %>
    <% if !@room.photos.blank? %>
      <span id="photo_check" class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>  
  </li>
  <li class="sidebar-item">
    <%= link_to "Amenities", amenities_room_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "Location", location_room_path, class: "sidebar-link active" %>
    <% if !@room.address.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
</ul>
<hr/>

<% is_ready = !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank? %>

<%= form_for @room do |f| %>
  <%= f.hidden_field :active, value: true %>
  <%= f.submit "Publish", id: "publish_button", class: "btn btn-normal btn-block", disabled: !is_ready %>
<% end %>

app/views/rooms/_rooms_list.html.erb
<% rooms.each do |room| %>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading preview">
          <%= image_tag room.cover_photo(:medium) %>
        </div>
        <div class="panel-body">
          <%= link_to room.listing_name, room %><br/>
          $<%= room.price %> - <%= room.home_type %> - <%= pluralize(room.bed_room, "bed") %>
          <div id="star_<%= room.id %>"></div> <%= pluralize(room.average_rating, "review") %>
        </div>
      </div>
    </div>

    <script>
      $('#star_<%= room.id %>').raty({
        path: '/assets',
        readOnly: true,
        score: <%= room.average_rating %>
      });
    </script>
<% end %>

app/views/rooms/amenities.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Amenities
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

              <div class="row form-group">
                <div class="col-md-4">
                  <%= f.check_box :is_tv %> TV
                </div>
                <div class="col-md-4">
                  <%= f.check_box :is_kitchen %> Kitchen
                </div>
                <div class="col-md-4">
                  <%= f.check_box :is_internet %> Internet
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-4">
                  <%= f.check_box :is_heating %> Heating
                </div>
                <div class="col-md-4">
                  <%= f.check_box :is_air %> Air Conditioning
                </div>
              </div>
              <br/><br/>

              <div class="text-center">
                <%= f.submit "Save", class: "btn btn-form" %>
              </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/create.html.erb
<h1>Room#create</h1>
<p>Find me in app/views/room/create.html.erb</p>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", rooms_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "Your Trips", your_trips_path, class: "sidebar-link" %></li>


    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Listings
      </div>
      <div class="panel-body">

        <% @rooms.each do |room| %>
          <div class="row">
            <div class="col-md-2">
              <%= image_tag room.cover_photo(:thumb) %>
            </div>
            <div class="col-md-7">
              <h4>
                <%= link_to room_path(room.id), data: {turbolinks: false } do %>
                <% if room.listing_name.blank? %>
                  Preview The room
                <% else %>
                  <%= room.listing_name %>
                <% end %>
                <% end %>
              </h4>
            </div>
            <div class="col-md-3 right">
              <%= link_to "Update", listing_room_path(room), class: "btn btn-form" %>
            </div>
          </div>
          <hr/>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/photo_upload.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Photos
      </div>

      <div class="panel-body">
        <div class="container">
          <div class="row">
            <div class="col-md-offset-3 col-md-6">
              <!-- PHOTOS UPLOAD GOES HERE -->

              <%= form_for @room, url: room_photos_path(@room), method: 'post', html: {multipart: true} do |f| %>
                <div class="row">
                  <div class="form-group">
                    <span class="btn btn-default btn-file text-babu">
                      <i class="fa fa-cloud-upload" aria-hidden="true"></i> Select Photos
                      <%= file_field_tag "images[]", type: :file, multiple: true %>
                    </span>
                  </div>
                </div>

                <div class="text-center">
                  <%= f.submit "Add Photos", class: "btn btn-form" %>
                </div>

              <% end %>
            </div>
          </div>
        <div id="photos"><%= render 'photos/photos_list' %></div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/update.html.erb
<h1>Room#update</h1>
<p>Find me in app/views/room/update.html.erb</p>